### ISSUE TITLE
Adding plugin to Ionic 4.0.0-beta.3 app hangs at splashscreen

### ISSUE THREAD

**Issue by paulsutherland** [ionic-team/cordova-plugin-ionic#128]
I am not sure if Ionic 4 is supported yet, but when adding the plugin to an Ionic 4.0.0-beta.3 app, it hangs at the splashscreen.

The app will successfully download the updates from deploy, but the app hangs on the splashscreen.  This happens on both the background and auto update method.

Steps to reproduce:

Create a new blank Ionic 4 app.
```
ionic start ionic4-deploy-example blank --type=angular
```
Add the plugin:
```
cordova plugin add cordova-plugin-ionic --save \
--variable APP_ID="XXXXXXXX" \
--variable CHANNEL_NAME="Production" \
--variable UPDATE_METHOD="background"
```
Commit changes and deploy to a channel called Production.

Run the app in xcode to see the output confirming the update, but hanging at reloading.

**Comment by nphyatt** [comment]
So I believe in v4 the `build` script defaults to a web assets only build and the `index.html` doesn't include the `cordova.js` script tag. That means that your "deploy snapshots" on pro our being build without including the cordova.js which will cause issues. We're looking to add some support to the CLI so that we can do a "deploy" specific build on pro for v4 but in the meantime you could write a little shell script or something that adds `<script src="cordova.js"></script>` to the index.html in your `www` directory and deploy should work.

**Comment by paulsutherland** [comment]
@nphyatt Thanks very much for your response.

I added the `<script src="cordova.js"></script>` tag to my index.html file and I confirm that deploy worked fine.

I'll look into tidying that up with a bash/npm script until such time as the CLI is updated.

Thank you,

Paul

**Comment by tomfebry** [comment]
I am having a same problem, does anyone know if this has been fixed?
Running the latest 4.0.0.beta.16
