### ISSUE TITLE
Question: Port change question

### ISSUE THREAD

**Issue by media4learning** [ionic-team/cordova-plugin-ionic#194]
Just a question with anyone that has experience with this plugin. Does this plugin support changing the port on the server. For example.

Steps: 
Initial development - <preference name="WKPort" value="8024" />

Publish binary version 1.0.0

Deploy an update.

Change port:
<preference name="WKPort" value="7777" />

Publish newer binary version 1.0.1

Deploy a newer update.

Will the plugin work as expected? Or would the port change cause unexpected behaviour?

**Comment by jcesarmobile** [comment]
The port change is done on cordova-plugin-ionic-webview, not here

Changing the port will not cause unexpected behaviour, but it will only change if they get the new binary with the port change implemented (1.0.1 in your example), it's not something that can be updated over the air. 

One thing to consider is that when you change the port, local data such us localStorage or IndexedDB is lost because of the domain changes.
