### ISSUE TITLE
Upgrading to version >=5.0 installs cordova-plugin-ionic-webview when not required

### ISSUE THREAD

**Issue by benmod** [ionic-team/cordova-plugin-ionic#210]
**Describe the bug**
Upgrading to version >=5.0 installs cordova-plugin-ionic-webview even if it is not listed as requirement until 5.1.6. This breaks crosswalk support as the plugin forces the use of its webview instead of the crosswalk webview. It is a silent issue as it is hard to notice until you test on older devices. 

**To Reproduce**
1. Update the cordova-plugin-ionic version to 5.0.0 (from 4.1.7 or below)
2. Make your app for Android
3. Open your app
4. It now uses the system webview instead of the crosswalk webview
5. This can be seen by testing for available JS functionalities or opening on older device

**Expected behavior**
The update should not install cordova-plugin-ionic-webview if it is not listed as requirement

**Additional context**
Crosswalk is still critical for some applications that absolutely require support of Android version 5 and below.

**Comment by jcesarmobile** [comment]
5.1.6 requires a specific version of the webview plugin, but from the 5.0.0 it required webview 2.0.0 plugin. 
In this commit you can see when the dependency was added, being both beta versions https://github.com/ionic-team/cordova-plugin-ionic/commit/970f5811c7938da5b79dddf850d5e7f26126755d

You can probably force the usage of crosswalk instead of ionic webview by adding this preference to the config.xml

`<preference name="webView" value="org.crosswalk.engine.XWalkWebViewEngine"/>`

But then appflow will probably not work as it requires some features implemented on our webview plugin that are not available on crosswalk.
