### ISSUE TITLE
Plugin is not compatible with cordova-plugin-crypt-file

### ISSUE THREAD

**Issue by SamarBakr** [ionic-team/cordova-plugin-ionic#218]
I'm using this plugin to deploy ionic 1 app and it worked fine,
but after install cordova-plugin-crypt-file the app didn't work with an error:

net::ERR_FILE_NOT_FOUND (file:///android_asset/www/+++/index.html)

my ionic info:
Ionic:
   ionic (Ionic CLI) : 4.10.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.22

Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : cordova-plugin-ionic 5.3.1,  cordova-plugin-ionic-webview 4.1.1, 
cordova-plugin-crypt-file 1.3.3

System:
   NodeJS : v8.10.0 (/usr/bin/node)
   npm    : 3.5.2
   OS     : Linux 4.15

**Comment by jcesarmobile** [comment]
Sorry, this is something the plugin authors should fix, not us. They are assuming the app files are loaded from `file:///android_asset/www`, but when using this plugin, the downloaded files are stored in a different place (because `file:///android_asset/www` is read only and we can't write there).
We provide a way of knowing the folder we load (`Ionic.WebView.getServerBasePath`), so that plugin should be updated to get the folder value instead of using that hardcoded value.
