### ISSUE TITLE
Deploy build fails to download on iOS (Capacitor)

### ISSUE THREAD

**Issue by korzeniowski** [ionic-team/cordova-plugin-ionic#220]
When downloading an Ionic Deploy build on an iOS device, HTTP requests start failing at around 95% of the update. This happens both when the update is triggered automatically and programmatically. The following error shows up multiple times in the Xcode logs:

```
[BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C159.1:2][0x13861ecf0] get output frames failed, state 8196
```

After about a minute, the update is aborted with the following additional errors logged out multiple times (task IDs and URLs replaced with `(...)` for legibility):
```
Task <(...)>.<1> finished with error - code: -1001
```
```
Download Error:Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x2805092c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=(...), NSErrorFailingURLKey=(...)
```

This is what it looks like in the Safari console with `downloadUpdate()` called programmatically and `progress` being logged out:
```
[Log] 93 (user-script:2, line 79, x2)
[Log] 94 (user-script:2, line 79, x63)
[Error] ERROR – Error: Uncaught (in promise): The request timed out.
Error: Uncaught (in promise): The request timed out.
	capacitorConsole (user-script:2:79)
	defaultErrorLogger (vendor.js:44320)
	handleError (vendor.js:44372)
	next (vendor.js:70119)
	(anonymous function) (vendor.js:66256)
	__tryOrUnsub (vendor.js:110228)
	next (vendor.js:110167)
	_next (vendor.js:110117)
	next (vendor.js:110094)
	next (vendor.js:109880)
	emit (vendor.js:66218)
	run (polyfills.js:3130)
	onHandleError (vendor.js:69441)
	runGuarded (polyfills.js:3143)
	microtaskDrainDone (polyfills.js:3669)
	drainMicroTaskQueue (polyfills.js:3572)
	invokeTask (polyfills.js:3475)
	timer (polyfills.js:5656)
```

On Android, the updates download without any issues.

Library versions:
`cordova-plugin-ionic` 5.4.3
`@capacitor/cli` 1.1.0
`@capacitor/core` 1.1.0
`@capacitor/ios` 1.1.0

**Comment by nphyatt** [comment]
@korzeniowski I just cut a new release `5.4.4` which hopefully helps with the issue...I think it may have been a  problem with too many requests at once. Also I think we need to add to the documentation specific to capacitor but can you ensure that you run `ionic deploy manifest` before you build the app and run on device? that command generates a `pro-manifest.json` file inside your built web directory which helps deploy to determine only the files it needs to download so that it can take advantage of reusing files/assets that may not have changed. If there isn't one in the bundled web app it will need to download all the files.

**Comment by korzeniowski** [comment]
@nphyatt thank you for the super-fast reply! Indeed, updating to `5.4.4` helped - the download is now batched and completes without issues. Also, regarding the manifest file, I somehow completely missed any info about it before - thanks a lot for bringing it to my attention!
