### ISSUE TITLE
Automatic update methods possibly ineffitient !?!

### ISSUE THREAD

**Issue by DavidTalamona** [ionic-team/cordova-plugin-ionic#27]
The two automatic update methods ("auto" and "background") are both called at app start.
Let's be honest, most people never really close / restart their apps.
The way those two automatics update methods are implemented at the moment would lead to a big number of outdated but frequently used apps. They would almost never be updated.

## Suggestion:
- In my opinion the "auto" method is not user friendly as it could lead to very long splash screen display without any feedback to the user. It should completely be dropped in favour of a better implementation of the "background" method.
- The "background" method would be much more useful if it would update not only on start of the app but as well on the apps pause / resume event.
The app should do an update check and download on start and resume. The next time it starts OR resumes it should apply the update.
Yes, this would restart the app when the update is applied, interrupting the users ”flow”, but this issue could be solved by applying some intelligence to the process. Let's say the update is not applied if the time between pause and resume is < 1 hour. I think this would prevent the user from losing context just because a call or something else interrupted his interaction with the app.

I set the live update method to "none" and implemented it manually, but I would change this back to "background" if this method would reliably update my apps in time and with some intelligence not interrupting the user or confusing him with unresponsive waiting screens.

**Comment by iconico** [comment]
Well said.
Especially with the new iOS on the iPhone X killing apps is getting harder to do, and Apple are moving away from it.

@DavidTalamona Would you be able to share your code on your own Javascript solution?

**Comment by nphyatt** [comment]
@DavidTalamona Thanks for the feedback! Sorry you went so long without a response! We just released v5 of the plugin yesterday and “background” mode is the default and indeed our suggested option. We’ve also added the ability to set a plugin variable for determining after how long the app is in the background we check for and apply an update on resume. It also brings with it a CDN and differential updates (only downloads files that have changed) to increase speed and decrease data usage. The API has changed but mostly only in name. There is a final version 4.2.0 which has both API’s which can help with upgrades but we suggest moving to 5.x.x ASAP because that’s where new features and bug fixes will go. I’m going to close this issue for now let me know if you have feedback or issues with the new plugin. Docs can be found [here](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin).
