### ISSUE TITLE
IonicDeploy.check returns 'true' for non-existing channel

### ISSUE THREAD

**Issue by lzoubek** [ionic-team/cordova-plugin-ionic#35]
Hello, 

I have setup `UPDATE_METHOD=none` in my ionic app. And I am implementing custom update logic. I am trying to detect a custom channel, which may or may not exist and in case it does not exist, I need to fallback to known channel (ie. `Master`)

I have a problem with `IonicDeploy.check` method, which returns `true` (this should mean there is an update available) when previously initialized with `channel` which does not exists.

`IonicDeploy.check` returns correctly `false` if a channel does exist, but is empty.

I think this should be fixed either in this plugin or even on backend, this behaviour is IMHO incorrect

Thank you

**Comment by yosigolan** [comment]
Hey.
i see that check always return true. even for the correct channel. how did you make it returning false?

**Comment by lzoubek** [comment]
I didn't - this is an issue in ionic pro backend. I gave up to my channel fallback logic until this gets fixed

**Comment by yosigolan** [comment]
i dont see an open issue. i will open one

**Comment by lzoubek** [comment]
can you link it here? so I can track it

**Comment by yosigolan** [comment]
https://github.com/ionic-team/cordova-plugin-ionic/issues/53

**Comment by yosigolan** [comment]
https://github.com/ionic-team/cordova-plugin-ionic/issues/53

**Comment by yosigolan** [comment]
this issue is in the same area: https://github.com/ionic-team/cordova-plugin-ionic/issues/53

**Comment by nphyatt** [comment]
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!
