### ISSUE TITLE
Error compiling (Swift version) Phonegap Build

### ISSUE THREAD

**Issue by luis-ordering** [ionic-team/cordova-plugin-ionic#36]
When I try to compile the application with phonegap build it gives me an error in iOS, in the logs this is:

> === BUILD TARGET Ordering App Test OF PROJECT Ordering App Test WITH CONFIGURATION Release ===
> 
> Check dependencies
> “Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
> “Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
> 
> ** ARCHIVE FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> Error code 65 for command: xcodebuild with args: -xcconfig,/private/project/cordova/build-release.xcconfig,-workspace,Ordering App Test.xcworkspace,-scheme,Ordering App Test,-configuration,Release,-destination,generic/platform=iOS,-archivePath,Ordering App Test.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/project/build/device,SHARED_PRECOMPS_DIR=/private/project/build/sharedpch
> /gimlet/bin/system_ruby: line 22: shell_session_update: command not found

I hope you can help me find a solution.
Thanks for your help.

**Comment by sergioaok** [comment]
@ionic-team please add phonegap support. Your plugin https://github.com/ionic-team/ionic-plugin-deploy was working fine. But now to this plugin which is supposed to be better cordova-plugin-ionic is not working because swift files were added in a very old version of swift. Unfortunately phonegap build does not support hooks so cordova-plugin-add-swift-support doesn’t work. 

Do you have any plans to update the plugin so it can work with phonegap build?

Please help we would be very thankful.

**Comment by mlynch** [comment]
Removed Swift in 561994a628c1d74b5c8bf6ea40716fd8f33e73d4
