### ISSUE TITLE
Manual download doesn't start

### ISSUE THREAD

**Issue by ziftytodd** [ionic-team/cordova-plugin-ionic#42]
I'm using this plugin with the "none" method so I can automatically update while the app itself is running rather than waiting for the next time the app starts. However, the actual code that is supposed to kick of the DownloadTask runs but the task doesn't ever start executing. I had to change the line in the `downloadUpdate` method from
`downloadTask.execute(url);`
to
`downloadTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, url);`
Once I did that, the task would execute as desired and actually download the update. Everything else worked fine.

**Comment by nphyatt** [comment]
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!
