### ISSUE TITLE
Check command always return true even if there is no udpate on the channel

### ISSUE THREAD

**Issue by yosigolan** [ionic-team/cordova-plugin-ionic#53]
when calling the check method, i am always receiving true even when i have the latest version.
my work around for that currently is to try download and if true is returned (from the download method) i know there is no update.

**Comment by jwieneke** [comment]
Any news on this one?

**Comment by JoeMeeks** [comment]
@yosigolan @jwieneke  I have the same issue. Proceeding with download, extract, and redirect works on iOS but on Android I get an error that the app has suddenly stopped.
```
        try {
            const update = Pro.deploy.check();
            if (update) {
                await Pro.deploy.download(self.download);
                await Pro.deploy.extract(self.extract);
                if (self.ui.loading.visible) {
                    self.ui.loading.show('Update complete', 'complete').then(() => {
                        setTimeout(self.ui.loading.hide, 3000);
                    });
                }
                await Pro.deploy.redirect();
            }
        } catch (ex) {
            console.error(ex.message);
            console.log(ex);
            Pro.monitoring.exception(ex);
        }
```

**Comment by jwieneke** [comment]
There were some issues with cordova-plugin-ionic on android.
I contacted the ionic pro support team and they deployed a fix.
The following suggestions worked for me:

> 
1. change the version from 4.1.3 to 4.1.4 for that plugin in both the package.json and the config.xml
2. rm -rf plugins platforms
3. npm i
4. re-add the platforms...
5. rebuild

**Comment by JoeMeeks** [comment]
Thanks @jwieneke. I have an open support ticket currently and their initial troubleshooting steps of upgrading ionic-app-scripts to 3.1.9 and cordova-plugin-ionic to the latest 4.1.7 and then remove/re-add plugins and platforms did not do the trick. If an Pro.deploy.check() sees any deploy on the channel (even an older deploy build or the same build as the packaged app build) it will return true.

**Comment by nphyatt** [comment]
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!
