### ISSUE TITLE
Offline mode or not connected to the internet

### ISSUE THREAD

**Issue by ermamud** [ionic-team/cordova-plugin-ionic#57]
Sometime when my phone is offline or my network coverage is sooo bad that all the connections start timing out, when the app is opening, it keeps spinning in the splash screen forever... I have my update mode set to `auto`, but I already tried in `background` with the same result.

Is there a way we can set a timeout to the plugin so after that amount of time stop waiting and allow the app to open ???

Regards,

**Comment by nphyatt** [comment]
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!
