### ISSUE TITLE
default UPDATE_METHOD should be 'none'

### ISSUE THREAD

**Issue by jgpATs2w** [ionic-team/cordova-plugin-ionic#68]
The discussion for this request is in:
https://stackoverflow.com/questions/49314433/why-my-ionic-3-apk-installs-old-code/49334169#49334169

**Comment by nphyatt** [comment]
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!
