### ISSUE TITLE
Cordova-plugin-ionic silently fails when semantic version is invalid

### ISSUE THREAD

**Issue by moscoso** [ionic-team/cordova-plugin-ionic#71]
For instance, if editing the config.xml and the version attribute of widget contains a value that is an invalid semantic version (such as 0.1.01) [invalid because it has a leading 0, specified here https://semver.org/]

The app fails all live deploys without warning or error when following the basic installation guide: https://ionicframework.com/docs/pro/deploy/setup/

The way I debugged the issue is to install the advanced deploy API (https://ionicframework.com/docs/pro/deploy/plugin-api.html), then run ionic cordova iOS and watch the console in xcode.

**Comment by nphyatt** [comment]
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!
