### ISSUE TITLE
The plugin reports 2 errors (instead of reporting warnings) when running on a platform without cordova (such as browser). 

### ISSUE THREAD

**Issue by moscoso** [ionic-team/cordova-plugin-ionic#72]
Just do an ionic-serve on a project using the Deploy Plugin as shown in this guide: https://ionicframework.com/docs/pro/deploy/plugin-api.html

Inspect the console and you will see these 2 errors:

the cordova-plugin-ionic plugin is not installed. Install it for better device information for runtime errors.
ionic-pro.module.min:1

Error loading deploy information. No Plugin Available
ionic-pro.module.min.js:1

Would like to see atleast warnings or better yet only report these errors if the platform is cordova. When the platform is not cordova, the plugin will never be available.

**Comment by kobvel** [comment]
Any progress on this one? 
Seems like it is primitive error handling.

**Comment by nphyatt** [comment]
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!
