### ISSUE TITLE
Debug build alert for code download stopped appearing

### ISSUE THREAD

**Issue by stellmaurer** [ionic-team/cordova-plugin-ionic#86]
I'm using the latest version of this plugin (4.1.7).

Ionic Live Deploy on iOS for my debug builds doesn’t ask me if I want the live-deploy version, even when WARN_DEBUG isn’t set to false. At one point in time, it did ask me if I wanted the most recent version whenever I ran a debug build (I clicked yes and downloaded the latest code each time), but the alert went away since then.

I have tried deleting the app from my phone and removing this plugin, and then re-adding the plugin and creating another build. I have also tried removing the iOS platform completely and re-adding it. None of that fixed the issue.

I suspect this may be a caching issue. I'm sorry if this ends up being a problem on my end. Any help would be appreciated :)

**Comment by media4learning** [comment]
I think what is happening here is when you download the deployed content, you are no longer on a debug build, so you won't get the warning unless you completely remove the app from the device and reinstall it using the cli. I have had major problems with this plugin up until 4.1.7. Since 4.1.7 was released, I have found it's working as expected. I have had to thoroughly test it because of all the problems and I can totally vouch for this version. Try uninstalling the app from the device and running ionic cordova run ios --device. You should get the debug warning again

**Comment by stellmaurer** [comment]
Thank you for getting back to me quickly.

I just tried that and the debug warning still didn't come up.

**Comment by nphyatt** [comment]
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!
