### ISSUE TITLE
Ionic Pro build failed due to conflict between cordova-plugin-ionic and cordova-plugin-zip

### ISSUE THREAD

**Issue by nguyentk90** [ionic-team/cordova-plugin-ionic#91]
Hi,

I'm using the latest version of cordova-plugin-ionic (4.1.7). I couldn't make a ios native package via Ionic Pro because the conflict of cordova-plugin-zip. 

Is there any plan to solve this issue?

Thank you,
Nguyen

**Comment by nphyatt** [comment]
Hi @nguyentk90!

`cordova-plugin-ionic@5.0.0` will be releasing very soon and it no longer relies on `cordova-plugin-zip` which will hopefully resolve your issues. If you'd like to try it out early you can install using the `rc` tag until official release. Our suggested path for fixing issues in v4 will be upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!
