### ISSUE TITLE
Live deploy - Update runs, although the version is the same/newest 

### ISSUE THREAD

**Issue by tanzmeier** [ionic-team/cordova-plugin-ionic#99]
Hi there,
I have a strange behavior with the live deploy function:

I have a certain progress with my code, so i stop developing and push/commit this code to my dev-branch on github. This branch is connected with ionic pro/live deploy and automatically builds a version into the dev-channel.
After that, i locally run “ionic cordova run android” and run this code on my phone.
At the moment, my update logic checks the dev-channel. And strangly it finds and runs an update.

How ist that possible?

The version on my phone and the version on my dev-channel are exactly the same. Why is the update triggered?

I hop, anyone can explain this to me.

Thank you

Skee

**Comment by nphyatt** [comment]
@tanzmeier Currently the only way to let the plugin know that 2 versions are the same or that one is newer that the other in order to prevent updates is through native versioning in the Pro dashboard. If you click the update in the list of builds in the Code tab you should see a tab on top for versioning. You can specify the minimum, equivalent, and maximum binary versions that the update should be applied to. We’re looking into making this process more automated and simple in the future. I’m going to go ahead and close this issue for now though. 

Hope that helps!
